version: "3"

vars:
  TF: tofu

includes:
  setup: tasks/Taskfile.setup.yaml

  # suicune-opal-ruby
  suicune:l0:opal:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/suicune/L0/opal
  suicune:l0:ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/suicune/L0/ruby
  suicune:l1:opal:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/suicune/L1/opal-ruby/opal
  suicune:l1:ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/suicune/L1/opal-ruby/ruby
  suicune:l1:opal-ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/suicune/L1/opal-ruby/generic

  # entei-amber-topaz
  entei:l0:topaz:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/topaz
  entei:l0:amber:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/amber
  entei:l1:topaz:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/topaz-amber/topaz
  entei:l1:amber:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/topaz-amber/amber
  entei:l1:topaz-amber:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/topaz-amber/generic

  # entei-opal-ruby
  entei:l0:opal:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/opal
  entei:l0:ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/ruby
  entei:l1:opal:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/opal-ruby/opal
  entei:l1:ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/opal-ruby/ruby
  entei:l1:opal-ruby:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/opal-ruby/generic

  # entei-mica-talc
  entei:l0:mica:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/mica
  entei:l0:talc:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L0/talc
  entei:l1:mica:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/mica-talc/mica
  entei:l1:talc:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/mica-talc/talc
  entei:l1:mica-talc:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/entei/L1/mica-talc/generic


  arceus:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      DIR: landscapes/arceus

tasks:
  kubectl:
    desc: Generate kubeconfig
    env:
      SLUGS: "pichu pikachu raichu suicune entei"
      PCLUSTERS: "entei"
      VCLUSTERS: "pichu pikachu raichu"
    cmds:
      - ./scripts/local/update-kubectl.sh
  sync:
    desc: Sync static and secrets
    cmds:
      - ./scripts/local/sync.sh
